import React from 'react'
import type { Metadata, Viewport } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const viewport: Viewport = {
  themeColor: '#ffffff'
}

export const metadata: Metadata = {
  title: "Hi! I'm Kyle!",
  description: 'Generated by create next app',
  icons: [
    {
      url: '/assets/maskable_icon_x192.png',
      type: 'image/png',
      sizes: '192x192',
      rel: 'apple-touch-icon'
    },
    {
      url: '/assets/maskable_icon_x384.png',
      type: 'image/png',
      sizes: '384x384',
      rel: 'apple-touch-icon'
    }
  ]
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
